<?php
/*
* Config file with each demo data
*/

return array(
	'business'	=>	array(
		'demoName'				=>	'Business',
		'liveURL'				=>	'http://nexarthemes.com/nexx/business/',
		'demoImg'				=>	'business.jpg',
		'xmlContentFile'		=>	'business.xml',
		'themeOptionsFile'		=>	'business.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'business-2'	=>	array(
		'demoName'				=>	'Business 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/business-2/',
		'demoImg'				=>	'business-2.jpg',
		'xmlContentFile'		=>	'business-2.xml',
		'themeOptionsFile'		=>	'business-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'classic-business'	=>	array(
		'demoName'				=>	'Classic Business',
		'liveURL'				=>	'http://nexarthemes.com/nexx/classic-business/',
		'demoImg'				=>	'classic-business.jpg',
		'xmlContentFile'		=>	'classic-business.xml',
		'themeOptionsFile'		=>	'classic-business.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'classic-business-2'	=>	array(
		'demoName'				=>	'Classic Business 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/classic-business-2/',
		'demoImg'				=>	'classic-business-2.jpg',
		'xmlContentFile'		=>	'classic-business-2.xml',
		'themeOptionsFile'		=>	'classic-business-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'company-presentation'	=>	array(
		'demoName'				=>	'Company Presentation',
		'liveURL'				=>	'http://nexarthemes.com/nexx/company-presentation/',
		'demoImg'				=>	'company-presentation.jpg',
		'xmlContentFile'		=>	'company-presentation.xml',
		'themeOptionsFile'		=>	'company-presentation.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'company-presentation-2'	=>	array(
		'demoName'				=>	'Company Presentation 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/company-presentation-2/',
		'demoImg'				=>	'company-presentation-2.jpg',
		'xmlContentFile'		=>	'company-presentation-2.xml',
		'themeOptionsFile'		=>	'company-presentation-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'corporate'	=>	array(
		'demoName'				=>	'Corporate',
		'liveURL'				=>	'http://nexarthemes.com/nexx/corporate/',
		'demoImg'				=>	'corporate.jpg',
		'xmlContentFile'		=>	'corporate.xml',
		'themeOptionsFile'		=>	'corporate.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'corporate-2'	=>	array(
		'demoName'				=>	'Corporate 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/corporate-2/',
		'demoImg'				=>	'corporate-2.jpg',
		'xmlContentFile'		=>	'corporate-2.xml',
		'themeOptionsFile'		=>	'corporate-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'new-corporate'	=>	array(
		'demoName'				=>	'New Corporate',
		'liveURL'				=>	'http://nexarthemes.com/nexx/new-corporate/',
		'demoImg'				=>	'new-corporate.jpg',
		'xmlContentFile'		=>	'new-corporate.xml',
		'themeOptionsFile'		=>	'new-corporate.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'creative-business'	=>	array(
		'demoName'				=>	'Creative Business',
		'liveURL'				=>	'http://nexarthemes.com/nexx/creative-business/',
		'demoImg'				=>	'creative-business.jpg',
		'xmlContentFile'		=>	'creative-business.xml',
		'themeOptionsFile'		=>	'creative-business.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'creative-business-2'	=>	array(
		'demoName'				=>	'Creative Business 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/creative-business-2/',
		'demoImg'				=>	'creative-business-2.jpg',
		'xmlContentFile'		=>	'creative-business-2.xml',
		'themeOptionsFile'		=>	'creative-business-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'landing-page'	=>	array(
		'demoName'				=>	'Landing Page',
		'liveURL'				=>	'http://nexarthemes.com/nexx/landing-page/',
		'demoImg'				=>	'landing-page.jpg',
		'xmlContentFile'		=>	'landing-page.xml',
		'themeOptionsFile'		=>	'landing-page.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'landing-page-2'	=>	array(
		'demoName'				=>	'Landing Page 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/landing-page-2/',
		'demoImg'				=>	'landing-page-2.jpg',
		'xmlContentFile'		=>	'landing-page-2.xml',
		'themeOptionsFile'		=>	'landing-page-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'modern-business'	=>	array(
		'demoName'				=>	'Modern Business',
		'liveURL'				=>	'http://nexarthemes.com/nexx/modern-business/',
		'demoImg'				=>	'modern-business.jpg',
		'xmlContentFile'		=>	'modern-business.xml',
		'themeOptionsFile'		=>	'modern-business.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'modern-business-2'	=>	array(
		'demoName'				=>	'Modern Business 2',
		'liveURL'				=>	'http://nexarthemes.com/nexx/modern-business-2/',
		'demoImg'				=>	'modern-business-2.jpg',
		'xmlContentFile'		=>	'modern-business-2.xml',
		'themeOptionsFile'		=>	'modern-business-2.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'organization'	=>	array(
		'demoName'				=>	'Organization',
		'liveURL'				=>	'http://nexarthemes.com/nexx/organization/',
		'demoImg'				=>	'organization.jpg',
		'xmlContentFile'		=>	'organization.xml',
		'themeOptionsFile'		=>	'organization.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'parallax-landing-page'	=>	array(
		'demoName'				=>	'Parallax Landing Page',
		'liveURL'				=>	'http://nexarthemes.com/nexx/parallax-landing-page/',
		'demoImg'				=>	'parallax-landing-page.jpg',
		'xmlContentFile'		=>	'parallax-landing-page.xml',
		'themeOptionsFile'		=>	'parallax-landing-page.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'startup'	=>	array(
		'demoName'				=>	'Startup',
		'liveURL'				=>	'http://nexarthemes.com/nexx/startup/',
		'demoImg'				=>	'startup.jpg',
		'xmlContentFile'		=>	'startup.xml',
		'themeOptionsFile'		=>	'startup.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'vcard'	=>	array(
		'demoName'				=>	'VCard',
		'liveURL'				=>	'http://nexarthemes.com/nexx/vcard/',
		'demoImg'				=>	'vcard.jpg',
		'xmlContentFile'		=>	'vcard.xml',
		'themeOptionsFile'		=>	'vcard.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'creative-agency'	=>	array(
		'demoName'				=>	'Creative Agency',
		'liveURL'				=>	'http://nexarthemes.com/nexx/creative-agency/',
		'demoImg'				=>	'creative-agency.jpg',
		'xmlContentFile'		=>	'creative-agency.xml',
		'themeOptionsFile'		=>	'creative-agency.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),
	'inner-pages'	=>	array(
		'demoName'				=>	'Inner Pages',
		'liveURL'				=>	'http://nexarthemes.com/nexx/',
		'demoImg'				=>	'inner-pages.jpg',
		'xmlContentFile'		=>	'inner-pages.xml',
		'themeOptionsFile'		=>	'inner-pages.json',
		'essentialGridFile'		=>	false,
		'revSliderZipFiles'		=>	false,
	),	
)
?>